sudo: false

language: node_js

dist: trusty

cache:
  directories:
    - node_modules

script:
  - node_modules/tupperware/deploy_to_container.sh

branches:
  only:
    - master
    - staging

notifications:
  webhooks: https://hxbot.dock-yard.io/hubot/travis-ci
